""" load pt files from a directory as numpy ndarrays which is generated by llama3_hook
Name of the pt files should be like: layer{layer_idx}_step{step_idx}_{tensor_name}_{RoPE}.pt
"""

import numpy as np
import torch
import os
from typing import Literal, Union
from pathlib import Path

def load(path: str | os.PathLike, layer: int, step: int, type: Literal["query", "key", "value", "attn_weights"], rope: bool = False, format: Literal["numpy", "torch"] = "torch") -> Union[np.ndarray, torch.Tensor]:
    """ load pt files from a directory as numpy ndarrays """
    # 组装文件路径，并读取 .pt 文件为 numpy ndarray，考虑 RoPE 后缀
    filename = f"layer{layer}_step{step}_{type}"
    if rope:
        filename += "_RoPE"
    filename += ".pt"
    file_path = Path(path) / filename
    tensor = torch.load(file_path, map_location="cpu")
    arr = tensor.cpu()
    if format == "numpy":
        arr = arr.numpy()
    return arr

def stat(path: str | os.PathLike) -> dict:
    """
    扫描路径下的文件，统计step总数和layer总数，统计不重复的类型集合
    """
    import re

    file_pat = re.compile(r"layer(\d+)_step(\d+)_([a-zA-Z_]+)\.pt$")
    steps = 0
    layers = 0
    types = set()
    for fname in os.listdir(path):
        m = file_pat.match(fname)
        if m:
            l, s, t = m.groups()
            layers = max(int(l), layers)
            steps = max(int(s), steps)
            types.add(t)

    res = {
        'layers': layers,
        'steps': steps,
        'types': sorted(types)
    }
    return res
